# Commands to start on workspace startup
tasks:
  - init: yarn install
    command: yarn build
  - init: terraform installation
    command: sudo curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add - && sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main" && sudo apt update && sudo apt install terraform
  
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
