# Commands to start on workspace startup
tasks:
  - init: yarn install
    command: yarn build
  - init: yum install
    command: sudo apt-get install yum
  - init: terraform install
    command: sudo yum install -y yum-utils && sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo && sudo yum -y install terraform
# Ports to expose on workspace startup
ports:
  - port: 8000
    onOpen: open-preview
